version: '3.9'

services:
  backend:
    build:
      context: ./backend
    environment:
      PORT: ${PORT:-8080}
      JWT_SECRET: ${JWT_SECRET:-change-me-in-production}
      JWT_TTL_SECONDS: ${JWT_TTL_SECONDS:-43200}
      CORS_ALLOWED_ORIGIN: ${CORS_ALLOWED_ORIGIN:-http://localhost}
    ports:
      - '8080:8080'

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: ${VITE_API_URL:-http://backend:8080/api}
    ports:
      - '80:80'
    depends_on:
      - backend
